"""empty message

Revision ID: 626b07fdc09c
Revises: 862f7d6e6fbb
Create Date: 2020-12-15 11:04:28.102262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626b07fdc09c'
down_revision = '862f7d6e6fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'admin')
    # ### end Alembic commands ###
