"""empty message

Revision ID: 862f7d6e6fbb
Revises: 8eac73f0982c
Create Date: 2020-12-15 10:05:56.449002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862f7d6e6fbb'
down_revision = '8eac73f0982c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('Roomname', sa.String(length=100), nullable=False))
    op.drop_column('workspace', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('workspace', 'Roomname')
    # ### end Alembic commands ###
